### ISSUE TITLE
Not compatible with ReWorked version

### ISSUE THREAD

**Issue by ArchiDreamZ** [mist475/MistLotrTweaks#2]
Crash on startup
[crash-2024-01-23_11.04.37-client.txt](https://github.com/mist475/MistLotrTweaks/files/14017821/crash-2024-01-23_11.04.37-client.txt)

[latest.log](https://github.com/mist475/MistLotrTweaks/files/14017822/latest.log)

**Comment by mist475** [comment]
In the config, disable fixJava12Compat. I only support the official lotr mod, no modified versions so if it breaks even after that I'm not gonna fix it
