### ISSUE TITLE
Config is throwing a fit.

### ISSUE THREAD

**Issue by MagmaSlime123** [mist475/MistLotrTweaks#3]
Title. The mod is all over the report.

https://pastebin.com/eWgtHMCh

**Comment by mist475** [comment]
That error means you have added a duplicate key in the config.
You probably tried to add a section for a tree type already described or you added a weight for a biome when that biome already had a weight for the specific tree type

**Comment by MagmaSlime123** [comment]
I regenerated the config. It still crashes.

**Comment by mist475** [comment]
Just to be sure, you regenerated the beehive config?

**Comment by MagmaSlime123** [comment]
Yep. I fully removed the MistLotrTweaks folder and let it regenerate.

**Comment by mist475** [comment]
And if you only run mistlotrtweaks, lotr, unimixins and efr?

**Comment by MagmaBro123** [comment]
Same issue.

**Comment by mist475** [comment]
What java version are you running and can you send a crash report from a fresh instance with just lotr, unimixins, mistlotrtweaks and efr?

**Comment by MagmaBro123** [comment]
I'm figuring out what mod might be causing this. Hang on a bit.

**Comment by MagmaSlime123** [comment]
Huh. It seems Item Physics is the cause. Not sure why your mod is blamed all over the report, though.

I've also noticed (even with no other mods besides UniMixins and LOTR) that beehives do not generate even without this wonky config breaking issue.

**Comment by mist475** [comment]
Beehives are quite rare, as such they're easy to miss. Some biomes have a much higher chance of bees, lossarnach for instance

I'll take a look at item physics sometime this week

**Comment by mist475** [comment]
I don't know how you reached the conclusion that item physics is the issue as it doesn't crash with that error for me, nor does it crash at all so item physics is not the issue. As the feature is fully working for me I suspect you took a crash file from a different profile

**Comment by MagmaSlime123** [comment]
Huh. You're right. Not sure why removing ItemPhysics fixed it. Adding it back no longer causes any crash. Weird.

**Comment by mist475** [comment]
let me know if you encounter this error again, I'll close the issue for now
